url=jdbc:mysql://localhost:3306/car_shop?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
username=root
password=1234
driver=com.mysql.cj.jdbc.Driver
changeLogFile=db/changelog/changelog-master.xml
databaseChangeLogTableName=DATABASECHANGELOG
databaseChangeLogLockTableName=DATABASECHANGELOGLOCK
defaultSchemaName=car_shop
outputDefaultSchema=true
outputDefaultCatalog=true
logLevel=INFO
logSql=true
fileEncoding=UTF-8
continueOnError=false
rollbackOnError=true
verbose=true